// Writes ui/props.js (the property table for the Property Inspector) from src/lib/properties.ts,
// so the inspector and the plugin can never disagree. Run through tsx.
import fs from "node:fs";
import { PROPERTIES, VIEW_LABEL } from "../src/lib/properties.ts";
import { TABS } from "../src/lib/applescript.ts";
import { defaultHoldToFire, HOLD_BY_DEFAULT } from "../src/lib/holdToFire.ts";
import { ENTRIES, uuidOf, isTab } from "../src/catalog/index.ts";
import { kebab } from "../src/lib/named.ts";

// What the Property Inspector needs to describe a named command key (path shown to the user, default hold-to-fire).
const commands = Object.fromEntries(
  ENTRIES.map((e) => [uuidOf(e), { title: e.title, path: isTab(e) ? ["Tab", e.tab] : e.menuPath, hold: e.holdToFire, unverified: !!e.unverified }]),
);

const out = `// GENERATED by scripts/gen-ui-data.mjs — do not edit.
window.CAPTURE = ${JSON.stringify({ properties: PROPERTIES.map((p) => ({ ...p, slug: kebab(p.id) })), views: VIEW_LABEL, tabs: TABS, holdByDefault: HOLD_BY_DEFAULT, commands })};
`;
fs.writeFileSync("com.rezabehjat.capture.sdPlugin/ui/props.js", out);
console.log("wrote ui/props.js");
