// Writes ui/props.js (the property table for the Property Inspector) from src/lib/properties.ts,
// so the inspector and the plugin can never disagree. Run through tsx.
import fs from "node:fs";
import { PROPERTIES, VIEW_LABEL } from "../src/lib/properties.ts";
import { TABS } from "../src/lib/applescript.ts";
import { defaultHoldToFire, HOLD_BY_DEFAULT } from "../src/lib/holdToFire.ts";

const out = `// GENERATED by scripts/gen-ui-data.mjs — do not edit.
window.CAPTURE = ${JSON.stringify({ properties: PROPERTIES, views: VIEW_LABEL, tabs: TABS, holdByDefault: HOLD_BY_DEFAULT }, null, 1)};
`;
fs.writeFileSync("com.rezabehjat.capture.sdPlugin/ui/props.js", out);
console.log("wrote ui/props.js");
