// GENERATED by scripts/gen-ui-data.mjs — do not edit.
window.CAPTURE = {
 "properties": [
  {
   "kind": "number",
   "id": "exposureAdjustment",
   "label": "Exposure",
   "short": "EXPOSURE",
   "min": -3,
   "max": 3,
   "wire": "f",
   "unit": "ev",
   "step": 0.1,
   "reset": 0
  },
  {
   "kind": "number",
   "id": "ambientLighting",
   "label": "Ambient",
   "short": "AMBIENT",
   "min": 0,
   "max": 1,
   "wire": "f",
   "unit": "percent",
   "step": 0.02,
   "reset": 0.5
  },
  {
   "kind": "number",
   "id": "bloom",
   "label": "Bloom",
   "short": "BLOOM",
   "min": 0,
   "max": 2,
   "wire": "f",
   "unit": "percent",
   "step": 0.04,
   "reset": 1
  },
  {
   "kind": "number",
   "id": "whiteBalance",
   "label": "White Balance",
   "short": "WHITE BAL",
   "min": 2500,
   "max": 10000,
   "wire": "f",
   "unit": "kelvin",
   "step": 100,
   "reset": 6500
  },
  {
   "kind": "number",
   "id": "fillLighting",
   "label": "Fill",
   "short": "FILL",
   "min": 0,
   "max": 2,
   "wire": "f",
   "unit": "percent",
   "step": 0.04,
   "reset": 1
  },
  {
   "kind": "number",
   "id": "hueClamp",
   "label": "Hue Clamp",
   "short": "HUE CLAMP",
   "min": 0,
   "max": 1,
   "wire": "f",
   "unit": "percent",
   "step": 0.02,
   "reset": 0.5
  },
  {
   "kind": "number",
   "id": "contrast",
   "label": "Contrast",
   "short": "CONTRAST",
   "min": 0,
   "max": 1,
   "wire": "f",
   "unit": "percent",
   "step": 0.02,
   "reset": 0.5
  },
  {
   "kind": "number",
   "id": "saturation",
   "label": "Saturation",
   "short": "SATURATION",
   "min": 0,
   "max": 1,
   "wire": "f",
   "unit": "percent",
   "step": 0.02,
   "reset": 0.5
  },
  {
   "kind": "number",
   "id": "flare",
   "label": "Flare",
   "short": "FLARE",
   "min": 0,
   "max": 2,
   "wire": "f",
   "unit": "percent",
   "step": 0.04,
   "reset": 1
  },
  {
   "kind": "number",
   "id": "flareSize",
   "label": "Flare Size",
   "short": "FLARE SIZE",
   "min": 0,
   "max": 2,
   "wire": "f",
   "unit": "percent",
   "step": 0.04,
   "reset": 1
  },
  {
   "kind": "number",
   "id": "flareAngle",
   "label": "Flare Angle",
   "short": "FLARE ANGLE",
   "min": 0,
   "max": 180,
   "wire": "f",
   "unit": "degrees",
   "step": 5,
   "reset": 0
  },
  {
   "kind": "number",
   "id": "flareStreaks",
   "label": "Flare Streaks",
   "short": "STREAKS",
   "min": 1,
   "max": 7,
   "wire": "i",
   "unit": "count",
   "step": 1,
   "reset": 4
  },
  {
   "kind": "bool",
   "id": "automaticExposure",
   "label": "Auto Exposure",
   "short": "AUTO EXP"
  },
  {
   "kind": "bool",
   "id": "laserFlickerEffect",
   "label": "Laser Flicker",
   "short": "LASER"
  }
 ],
 "views": {
  "0": "Alpha",
  "1": "Beta",
  "2": "Gamma",
  "live": "Live view"
 },
 "tabs": [
  "Design",
  "Fixtures",
  "Universes",
  "Media",
  "Snapshots",
  "Library"
 ],
 "holdByDefault": [
  "Delete",
  "Unpatch",
  "Remove Filters",
  "Remove Gobos",
  "Cut",
  "Paste"
 ]
};
